module.exports = {
  arabic: {
    // home page
    title: 'شجرة الحياة',
    description: 'هذا التطبيق عبارة عن منصة بين كل من يرغب بالتطوع ويبحث عن اطار ملائم وجمعيات باحثة عن متطوعين',
    frontPageButton: 'متطوع',
    frontPageOrgButton: 'منظمة',
    // list page
    listHeader: 'فرص للتطوع',
    roleDesc: 'تفاصيل عن العمل التطوعي',
    OrgDesc: 'شرح مختصر عن الجمعية',
    moreInfoBtn: 'للمزيد من المعلومات',
    lessInfoBtn: 'معلومات اقل',
    applyButton: 'تطوع',
    // volunteer form page
    formHeader: 'استمارة التطوع',
    formFN: 'الاسم الشخصي',
    formLN: 'اسم العائلة',
    formAge: 'العمر',
    formAvail: 'امكانية التطوع حسب (ساعات الفراغ او الايام ',
    formPhone: 'رقم الهاتف',
    formEmail: 'البريد الالكتروني:',
    formSubmit: 'ارسل',
    // validate volunteer form
    volFormFNErorr: 'ادخل الاسم الشخصي',
    volFormLNErorr: 'ادخل اسم العائلة',
    volFormAgeErorr: 'ادخل عمرك',
    volFormAgeISintErorr: 'العمر 16 وما فوق',
    volFormAvailErorr: 'ادخل امكانية التطوع',
    volFormPhoneEmptyErorr: 'ادخل رقم الهاتف',
    volFormPhoneIsIntError: 'ادخل ارقام فقط',
    volFormPhoneLengthError: 'ادخل رقم هاتف يحتوي على 10 خانات',
    volFormEmailError: 'ادخل البريد الالكتروني',
    volFormIsEmailError: 'ادخل البريد الالكتروني بالصيغة الصحيحه',
    // datasubmit page
    submitHeader: 'العملية تمت بنجاح',
    // org form page
    orgFormHeader: 'استمارة الجمعية',
    orgFormIntro: 'شجرة الحياة هو تطبيق بني بهدف الربط بين المنظمات الباحثة عن متطوعين وبين اناس راغبين بالتطوع باطار منظم ,لذلك كمنظمة يرجى تعبئة الاستمارة وسيتم التواصل معكم عن توافر عدد المتطوعين الملائم',
    orgFormName: 'اسم المنظمة',
    orgFormDesc: 'شرح عن المنظمة',
    orgFormRolename: 'العمل التطوعي',
    orgFormRoleDesc: 'تفاصيل عن العمل التطوعي',
    orgFormVolnum: 'عدد المتطوعين',
    orgFormStartdate: 'تاريخ البداية',
    orgFormEnddate: 'تاريخ الانتهاء',
    orgFormPhonenum: 'رقم الهاتف',
    orgFormEmail: 'البريد الالكتروني',
    orgFormSubmit: 'ارسل',
    // validate orgForm
    orgNameError: 'ادخل اسم المنظمة',
    orgDescError: 'ادخل شرح عن المنظمة',
    orgRolenameError: 'ادخل اسم العمل التطوعي',
    orgRoleDescError: 'ادخل شرح عن العمل التطوعي',
    orgVolnumError: 'ادخل عدد المتطوعين',
    orgVolnumIntError: 'ادخل عدد متطوعين اكبر من صفر',
    orgStartdateError: 'ادخل تاريخ البداية',
    orgStartdateFormtError: 'ادخل التاريخ بالصيغة الصحيحة',
    orgStartdateIsAfterError: 'ادخل تاريخ ملائم',
    orgEnddateError: 'ادخل تاريخ الانتهاء',
    orgEnddateFormtError: 'ادخل التاريخ بالصيغة الصحيحة',
    orgEnddateIsAfterError: 'ادخل التاريخ الملائم',
    orgPhoneEmptyError: 'ادخل رقم الهاتف',
    orgPhoneIsIntError: 'ادخل ارقام فقط',
    orgPhoneLengthError: 'ادخل رقم هاتف يحتوي على 10 خانات',
    orgEmailError: 'ادخل البريد الالكتروني',
    orgIsEmailError: 'ادخل البريد الالكتروني بالصيغة الصحيحة'

  },
  english: {
    title: 'Tree Of Life',
    description: 'An app to help connect volunteers with organisation look for them',
    frontPageButton: 'Volunteer!',
    frontPageOrgButton: 'Organisation Login',
    // list page
    listHeader: 'Opportunities',
    roleDesc: 'Role Description: ',
    OrgDesc: 'Organisation Description: ',
    moreInfoBtn: 'More Info',
    applyButton: 'Apply',
    // volunteer form page
    formHeader: 'Application Form',
    formFN: 'First Name',
    formLN: 'Last Name',
    formAge: 'Age:',
    formAvail: 'Please indicate what days and times you would be avaliable: ',
    formPhone: 'Phone Number',
    formEmail: 'Email Address:',
    formSubmit: 'Submit Details',
    // validate volunteer form
    volFormFNErorr: '',
    volFormLNErorr: '',
    volFormAgeErorr: '',
    volFormAgeISintErorr: '',
    volFormAvailErorr: '',
    volFormPhoneEmptyErorr: '',
    volFormPhoneIsIntError: '',
    volFormPhoneLengthError: '',
    volFormEmailError: '',
    volFormIsEmailError: '',
    // datasubmit page
    submitHeader: '',
    // org form page
    orgFormHeader: 'Add A New Volunteer Opportunity',
    orgFormIntro: 'Tree of Life is an app that hopes to connect organisations with volunteers looking to help. As an organisation, please use the form below to fill out the details of a volunteering opportunity for which you are looking for helpers. We will then contact you with information on volunteers who register an interest.',
    orgFormName: 'Organisation Name: ',
    orgFormDesc: 'Organisation Description: ',
    orgFormRolename: 'Role Name: ',
    orgFormRoleDesc: 'Role Description: ',
    orgFormVolnum: 'Number of Volunteers required: ',
    orgFormStartdate: 'Start Date: ',
    orgFormEnddate: 'End Date: ',
    orgFormPhonenum: 'Contact Number: ',
    orgFormEmail: 'Contact Email: ',
    orgFormSubmit: 'Submit',
    // validate orgForm
    orgNameError: 'Organisation Name Required',
    orgDescError: 'ادخل شرح عن المنظمة',
    orgRolenameError: 'ادخل اسم العمل التطوعي',
    orgRoleDescError: 'ادخل شرح عن العمل التطوعي',
    orgVolnumError: 'ادخل عدد المتطوعين',
    orgVolnumIntError: 'ادخل عدد متطوعين اكبر من صفر',
    orgStartdateError: 'ادخل تاريخ البداية',
    orgStartdateFormtError: 'ادخل التاريخ بالصيغة الصحيحة',
    orgStartdateIsAfterError: 'ادخل تاريخ ملائم',
    orgEnddateError: 'ادخل تاريخ الانتهاء',
    orgEnddateFormtError: 'ادخل التاريخ بالصيغة الصحيحة',
    orgEnddateIsAfterError: 'ادخل التاريخ الملائم',
    orgPhoneEmptyError: 'ادخل رقم الهاتف',
    orgPhoneIsIntError: '',
    orgPhoneLengthError: 'اخل رقم هاتف يحتوي على 10 خانات',
    orgEmailError: 'ادخل البريد الالكتروني',
    orgIsEmailError: 'ادخل البريد الالكتروني بصيغة صحيحة'

  }
};
