module.exports = {
  arabic: {
    // home page
    title: 'شجرة الحياة',
    description: 'هذا التطبيق عبارة عن منصة بين كل من يرغب بالتطوع ويبحث عن اطار ملائم وجمعيات باحثة عن متطوعين',
    frontPageButton: 'متطوع',
    frontPageOrgButton: 'منظمة',
    // list page
    listHeader: 'فرص للتطوع',
    roleDesc: 'تفاصيل عن العمل التطوعي',
    OrgDesc: 'شرح مختصر عن الجمعية',
    moreInfoBtn: 'للمزيد من المعلومات',
    lessInfoBtn: 'معلومات اقل',
    applyButton: 'تطوع',
    // volunteer form page
    organisation: 'المنظمة',
    until: 'حتى',
    formHeader: 'استمارة التطوع',
    formFN: 'الاسم الشخصي',
    formLN: 'اسم العائلة',
    formAge: 'العمر',
    formAvail: 'امكانية التطوع حسب (ساعات الفراغ او الايام ',
    formPhone: 'رقم الهاتف',
    formEmail: 'البريد الالكتروني:',
    formSubmit: 'ارسل',
    // validate volunteer form
    volFormFNErorr: 'ادخل الاسم الشخصي',
    volFormLNErorr: 'ادخل اسم العائلة',
    volFormAgeErorr: 'ادخل عمرك',
    volFormAgeISintErorr: 'العمر 16 وما فوق',
    volFormAvailErorr: 'ادخل امكانية التطوع',
    volFormPhoneEmptyErorr: 'ادخل رقم الهاتف',
    volFormPhoneIsIntError: 'ادخل ارقام فقط',
    volFormPhoneLengthError: 'ادخل رقم هاتف يحتوي على 10 خانات',
    volFormEmailError: 'ادخل البريد الالكتروني',
    volFormIsEmailError: 'ادخل البريد الالكتروني بالصيغة الصحيحه',
    // datasubmit page
    submitHeader: 'العملية تمت بنجاح',
    // org form page
    orgFormHeader: 'استمارة الجمعية',
    orgFormIntro: 'شجرة الحياة هو تطبيق بني بهدف الربط بين المنظمات الباحثة عن متطوعين وبين اناس راغبين بالتطوع باطار منظم ,لذلك كمنظمة يرجى تعبئة الاستمارة وسيتم التواصل معكم عند توافر عدد المتطوعين الملائم',
    orgFormName: 'اسم المنظمة',
    orgFormDesc: 'شرح عن المنظمة',
    orgFormRolename: 'العمل التطوعي',
    orgFormRoleDesc: 'تفاصيل عن العمل التطوعي',
    orgFormVolnum: 'عدد المتطوعين',
    orgFormStartdate: 'تاريخ البداية',
    orgFormEnddate: 'تاريخ الانتهاء',
    orgFormPhonenum: 'رقم الهاتف',
    orgFormEmail: 'البريد الالكتروني',
    orgFormSubmit: 'ارسل',
    // validate orgForm
    orgNameError: 'ادخل اسم المنظمة',
    orgDescError: 'ادخل شرح عن المنظمة',
    orgRolenameError: 'ادخل اسم العمل التطوعي',
    orgRoleDescError: 'ادخل شرح عن العمل التطوعي',
    orgVolnumError: 'ادخل عدد المتطوعين',
    orgVolnumIntError: 'ادخل عدد متطوعين اكبر من صفر',
    orgStartdateError: 'ادخل تاريخ البداية',
    orgStartdateFormtError: 'ادخل التاريخ بالصيغة الصحيحة',
    orgStartdateIsAfterError: 'ادخل تاريخ ملائم',
    orgEnddateError: 'ادخل تاريخ الانتهاء',
    orgEnddateFormtError: 'ادخل التاريخ بالصيغة الصحيحة',
    orgEnddateIsAfterError: 'ادخل التاريخ الملائم',
    orgPhoneEmptyError: 'ادخل رقم الهاتف',
    orgPhoneIsIntError: 'ادخل ارقام فقط',
    orgPhoneLengthError: 'ادخل رقم هاتف يحتوي على 10 خانات',
    orgEmailError: 'ادخل البريد الالكتروني',
    orgIsEmailError: 'ادخل البريد الالكتروني بالصيغة الصحيحة',
    mongoIDError: 'هناك خلل في قاعدة البيانات',
    password: 'كلمة المرور',
    passwordSubmit: 'اضغط',
    wrongPassword: 'كلمة المرور خاطئة',
    numApplied: 'لا يوجد متطوعين حتى الان !'
  },
  english: {
    title: 'Tree Of Life',
    description: 'An app to help connect volunteers with organisation look for them',
    frontPageButton: 'Volunteer Now!',
    frontPageOrgButton: 'Organisation Login',
    // list page
    listHeader: 'Opportunities',
    roleDesc: 'Role Description: ',
    OrgDesc: 'Organisation Description: ',
    moreInfoBtn: 'More Info',
    applyButton: 'Apply',
    // volunteer form page
    organisation: 'By Organisation: ',
    until: 'until',
    formHeader: 'Application Form',
    formFN: 'First Name',
    formLN: 'Last Name',
    formAge: 'Age:',
    formAvail: 'Please indicate what days and times you would be avaliable: ',
    formPhone: 'Phone Number',
    formEmail: 'Email Address:',
    formSubmit: 'Submit Details',
    // validate volunteer form
    volFormFNErorr: 'First Name required',
    volFormLNErorr: 'Last Name required',
    volFormAgeErorr: 'Age required',
    volFormAgeISintErorr: 'Age must be a number over 15',
    volFormAvailErorr: 'Please add avaliability',
    volFormPhoneEmptyErorr: 'Phone number required',
    volFormPhoneIsIntError: 'Phone number must be only numbers',
    volFormPhoneLengthError: 'Phone number length must be between 9 and 11 characters',
    volFormEmailError: 'Email required',
    volFormIsEmailError: 'Email is in wrong format',
    // datasubmit page
    submitHeader: 'Your details have been added to the database',
    // org form page
    orgFormHeader: 'Add A New Volunteer Opportunity',
    orgFormIntro: 'Tree of Life is an app that hopes to connect organisations with volunteers looking to help. As an organisation, please use the form below to fill out the details of a volunteering opportunity for which you are looking for helpers. We will then contact you with information on volunteers who register an interest.',
    orgFormName: 'Organisation Name: ',
    orgFormDesc: 'Organisation Description: ',
    orgFormRolename: 'Role Name: ',
    orgFormRoleDesc: 'Role Description: ',
    orgFormVolnum: 'Number of Volunteers required: ',
    orgFormStartdate: 'Start Date: ',
    orgFormEnddate: 'End Date: ',
    orgFormPhonenum: 'Contact Number: ',
    orgFormEmail: 'Contact Email: ',
    orgFormSubmit: 'Submit',
    // validate orgForm
    orgNameError: 'Organisation Name Required',
    orgDescError: 'Organisation Description Required',
    orgRolenameError: 'Role Name required',
    orgRoleDescError: 'Role description required',
    orgVolnumError: 'Please specify the number of volunteers you need',
    orgVolnumIntError: 'Volunteer number must be a number',
    orgStartdateError: 'Start date required',
    orgStartdateFormtError: 'Start date in the wrong format (please use the calendar)',
    orgStartdateIsAfterError: 'Start date cannot be in the past',
    orgEnddateError: 'End date required',
    orgEnddateFormtError: 'End date in the wrong format (please use the calendar)',
    orgEnddateIsAfterError: 'End date cannot be before the start date',
    orgPhoneEmptyError: 'Contact number required',
    orgPhoneIsIntError: 'Phone number in wrong format',
    orgPhoneLengthError: 'Phone number is the wrong length',
    orgEmailError: 'Email required',
    orgIsEmailError: 'Email not in correct format',
    mongoIDError: 'Something went wrong with the database ID',
    password: 'Password:',
    passwordSubmit: 'Submit',
    wrongPassword: 'Wrong Password',
    numApplied: 'No volunteers yet!'
  }
};
